### ISSUE TITLE
Heroku button no longer works: "Could not find prisma-fmt binary"

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone-6-heroku-example#8]
```
-----> Build
       Running build (yarn)
       yarn run v1.22.19
       $ keystone build && keystone prisma migrate deploy
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
       Error: Could not find prisma-fmt binary. Searched in /tmp/build_5daef6db/node_modules/@prisma/sdk/prisma-fmt-debian-openssl-3.0.x and /tmp/build_5daef6db/node_modules/@prisma/prisma-fmt-debian-openssl-3.0.x
           at resolveBinary (/tmp/build_5daef6db/node_modules/@prisma/sdk/dist/resolveBinary.js:92:9)
           at Object.formatSchema (/tmp/build_5daef6db/node_modules/@prisma/sdk/dist/engine-commands/formatSchema.js:41:25)
           at getCommittedArtifacts (/tmp/build_5daef6db/node_modules/@keystone-6/core/dist/artifacts-4c43950a.cjs.prod.js:416:13)
           at Object.validateCommittedArtifacts (/tmp/build_5daef6db/node_modules/@keystone-6/core/dist/artifacts-4c43950a.cjs.prod.js:435:21)
           at Object.build (/tmp/build_5daef6db/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.prod.js:608:3)
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
-----> Build failed
```

**Comment by molomby** [comment]
Seems to fail consistently; 3 for 3 attempts.

Possibly bumping the Keystone core version past 2.1.0 [would help](https://github.com/keystonejs/keystone/discussions/7461#discussioncomment-3328734)?
